name: Deploy kpi-onepage on self-hosted server

on:
  push:
    branches:
      - main        # ถ้า deploy จาก branch อื่น เปลี่ยนตามจริง

jobs:
  deploy:
    runs-on: self-hosted    # ใช้ runner ที่อยู่บน server เครื่องนี้

    steps:
      - name: Go to project folder
        run: |
          cd /home/phoubon-kpionepage/htdocs/kpi-onepage.phoubon.in.th
          pwd
          ls

      - name: Git pull latest code
        run: |
          cd /home/phoubon-kpionepage/htdocs/kpi-onepage.phoubon.in.th
          git pull origin main

      - name: Install dependencies
        working-directory: /home/phoubon-kpionepage/htdocs/kpi-onepage.phoubon.in.th
        run: npm ci

      - name: Generate Prisma Client
        working-directory: /home/phoubon-kpionepage/htdocs/kpi-onepage.phoubon.in.th
        run: npx prisma generate

      - name: Build Next.js
        working-directory: /home/phoubon-kpionepage/htdocs/kpi-onepage.phoubon.in.th
        run: npm run build


      - name: Restart app with PM2 (no duplicate)
        working-directory: /home/phoubon-kpionepage/htdocs/kpi-onepage.phoubon.in.th
        run: |
          if pm2 describe kpi-onepage > /dev/null 2>&1; then
            echo "PM2 process exists -> restart"
            pm2 restart kpi-onepage
          else
            echo "PM2 process not found -> start new"
            pm2 start "npm start" --name kpi-onepage
          fi
          pm2 save
